### ISSUE TITLE
Animation gets progressively darker

### ISSUE THREAD

**Issue by polovero** [Animator-Anon/Animator#44] opened 2023-01-01 22:16 UTC
Hello developers, I really appreciate the animator script so much, I've been spending the last few days playing with it and I'm getting some interesting results.  The problem I'm having though is that the animation gets progressively darker.  I've tried changing various parameters to no avail. I'm using the 1.4 model because the newer ones render slower on my Mac M1, and I don't need ultra-realistic images.  I'm basically doing a zoom-in on some simple illustrations.  The going dark thing is making the animations unusable though.  Any suggestions?

**Comment by Animator-Anon** [comment] 2023-01-03 10:20
I have no idea what could be causing this, but I also haven't tried to run it on a Mac.
Can you provide a short example set of keyframes that I can use to reproduce the issue?
Can you try and do an img2img through the UI without using my script at all and see if that also has issues?

**Comment by polovero** [comment] 2023-01-03 20:44
Here are two examples, and I have many more!
1.) Geisha Yellow
https://user-images.githubusercontent.com/121645424/210434670-f1d895af-a2f9-4a37-94c0-2aa33e42c9ba.mp4
2.) Geisha BW (please ignore the last frame, I accidentally caught the beginning of another clip in post-production)
https://user-images.githubusercontent.com/121645424/210434710-87a68bd3-726c-4041-b8d9-6d0cc476f9a4.mp4

Here is are the inputs:
 {
    "Create GIF": false,
    "Create MP4": false,
    "Create WEBM": false,
    "Total Time (s)": 10.0,
    "FPS": 15.0,
    "Seed March": false,
    "Smoothing Frames": 0,
    "Initial De-noising Strength": 0.25,
    "Initial Zoom Factor": 1.4,
    "Initial X Pixel Shift": 0.0,
    "Initial Y Pixel Shift": 0.0,
    "Rotation": 0.0,
    "Prop Folder": "",
    "Prompt Template Positive": "",
    "Prompt Template Negative": "",
    "Keyframe Data": "1 | prompt | a woman in white long-sleeved shirt writing a to-do list, looking down from above  | |\n2 | prompt | a hand holding a reed pen writing | \n3 | prompt |  a line of text with swirls | \n4| prompt |  lines of text  | \n5| prompt |  swirls  | \n7| prompt |  neurons  | \n10 | prompt | abstract symbols | \n"
}


The second one:
{
    "Create GIF": false,
    "Create MP4": false,
    "Create WEBM": true,
    "Total Time (s)": 10.0,
    "FPS": 15.0,
    "Seed March": false,
    "Smoothing Frames": 0,
    "Initial De-noising Strength": 0.4,
    "Initial Zoom Factor": 1.3,
    "Initial X Pixel Shift": 20.0,
    "Initial Y Pixel Shift": 0.0,
    "Rotation": 0.0,
    "Prop Folder": "",
    "Prompt Template Positive": "Sumi-e ink illustration with brushstrokes, black and white and red, high contrast",
    "Prompt Template Negative": "writing, watermark",
    "Keyframe Data": "2 | prompt | a woman in white long-sleeved shirt writing a to-do list, looking down from above, black and white and red\n5 | prompt | a hand writing with a pen, a line of text with swirls | \n10 | prompt | a neural network | \n"
}

I've done further tests changing denoising and CFG scale parameters, asking for light images, etc, to no avail.

I don't have a problem with img2img.  This is a sequential thing, the more images, the darker it gets, eventually.  I would love to leave the script running for a long time to get a longer video, but the images always end up dark so I'm holding off for now. I really like the simplicity of the script though so I would love to figure this out.

Thank you for any feedback.

Veronica

**Comment by Animator-Anon** [comment] 2023-01-04 07:03
Yes you are right, something has broken and I am not sure what. Maybe something changed in WebUI.

**Comment by polovero** [comment] 2023-01-05 11:09
Do you know if anymore updates are planned for this script? My next step is to try out deforum, although that will take up the little space hard-drive space I have left on my Mac and I was hoping to avoid that.

**Comment by Animator-Anon** [comment] 2023-01-10 06:38
If I can figure out what is causing the darkness, I will update it yes. However I don't have much time to spend on it. Best hedge your bets and expand your portfolio!

**Comment by polovero** [comment] 2023-01-10 06:52
I've moved on to Deforum for Automatic1111 and there is no darkness issue there. I loved the simplicity of the Animator Script though, good job.  Thanks for everything and enjoy your current and future projects.

**Comment by Animator-Anon** [comment] 2023-01-11 09:15
For what it is worth, I found out the problem was introduced into the WebUI in the following pull request:
https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/5644

It was easy enough to add the old functions to my scripts, should be fixed unless I broke something else. How ever you do it, have fun animating!

**Closed by Animator-Anon** 2023-01-11 09:15 UTC
